# Imports

In [1]:
import torch
import numpy as np

# Tensors

## Simple Examples

In [ ]:
tensor = torch.tensor([1,2])
tensor, tensor.shape

(tensor([1, 2]), torch.Size([2]))

In [ ]:
tensor = torch.tensor([[1,2], [3,4], [5,6]])

print(f'Tensor shape: {tensor.shape}\n')
tensor

Tensor shape: torch.Size([3, 2])



tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor = torch.tensor([[[1,2], [3,4], [5,6]],
                       [[1,2], [3,4], [5,6]]])

print(f'Tensor shape: {tensor.shape}\n')
tensor

Tensor shape: torch.Size([2, 3, 2])



tensor([[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]])

## Tensor types

In [ ]:
# Float Tensor
tensor = torch.tensor([[1, 2], [3,4]], dtype=torch.float)

tensor

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
# Float Tensor
tensor = torch.FloatTensor([[1, 2], [3,4]])

tensor

tensor([[1., 2.],
        [3., 4.]])

## Operations

### From Numpy to Pytorch Tensor

In [ ]:
# Numpy array
array = np.array([[1, 2], [3,4]])
print(f'Numpy Array:\n{array}\n\n')

tensor = torch.FloatTensor(array)
tensor

Numpy Array:
[[1 2]
 [3 4]]




tensor([[1., 2.],
        [3., 4.]])

### Tensor initialization

In [ ]:
# All zeros tensor
tensor = torch.zeros([5,4])

print(f'Tensor shape: {tensor.shape}\n')
tensor

Tensor shape: torch.Size([5, 4])



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# All ones tensor
tensor = torch.ones([5,4])

print(f'Tensor shape: {tensor.shape}\n')
tensor

Tensor shape: torch.Size([5, 4])



tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# All random value tensor
tensor = torch.rand([5,4])

print(f'Tensor shape: {tensor.shape}\n')
tensor

Tensor shape: torch.Size([5, 4])



tensor([[0.4678, 0.3765, 0.0776, 0.8626],
        [0.7065, 0.9140, 0.6200, 0.1297],
        [0.4672, 0.7617, 0.2017, 0.9894],
        [0.6748, 0.4383, 0.2147, 0.0890],
        [0.7210, 0.3155, 0.3530, 0.2945]])

In [ ]:
# Arange
tensor = torch.arange(0, 10)

print(f'Tensor shape: {tensor.shape}\n')
tensor

Tensor shape: torch.Size([10])



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Aritmetics

In [ ]:
tensor = torch.Tensor([[1,2, 3,4]])

print(f'Tensor shape: {tensor.shape}\n')
tensor

Tensor shape: torch.Size([1, 4])



tensor([[1., 2., 3., 4.]])

In [ ]:
# Multiplication

print(f'Starting Tensor:\n{tensor}\n')

m1 = tensor * tensor
m2 = tensor.mul(tensor)

print(f'm1: \n{m1}\n')
print(f'm2: \n{m2}\n')

#  arange - reshape - cat - logical statements - indexing - slicing - conversion to other formats

Starting Tensor:
tensor([[1., 2., 3., 4.]])

m1: 
tensor([[ 1.,  4.,  9., 16.]])

m2: 
tensor([[ 1.,  4.,  9., 16.]])



In [ ]:
# Sum
print(f'Starting Tensor: \n{tensor}\n')

s1 = tensor + tensor
s2 = tensor.add(tensor)

print(f's1: \n{s1}\n')
print(f's2: \n{s2}\n')

Starting Tensor: 
tensor([[1., 2., 3., 4.]])

s1: 
tensor([[2., 4., 6., 8.]])

s2: 
tensor([[2., 4., 6., 8.]])



### Shape transformation

In [ ]:
tensor = torch.Tensor([[[1,2,3], [4,5,6]]])

print(f'Starting Tensor: \n\n{tensor}\n\n{tensor.shape}\n----------------------\n\n')

# Reshape
r = tensor.reshape(1,3,2)
print(f'Reshaped tensor:\n\n{r}\n\n{r.shape}\n\n---------------------\n\n')

# Squeeze
s = tensor.squeeze()
print(f'Squeezed tensor:\n\n{s}\n\n{s.shape}\n\n---------------------\n\n')

# Flattening
f = tensor.flatten()
print(f'Flattening tensor:\n\n{f}\n\n{f.shape}\n\n---------------------\n\n')

# Transpose
t = tensor.transpose(1,2)
print(f'Transposing tensor:\n\n{t}\n\n{t.shape}\n\n---------------------\n\n')

Starting Tensor: 

tensor([[[1., 2., 3.],
         [4., 5., 6.]]])

torch.Size([1, 2, 3])
----------------------


Reshaped tensor:

tensor([[[1., 2.],
         [3., 4.],
         [5., 6.]]])

torch.Size([1, 3, 2])

---------------------


Squeezed tensor:

tensor([[1., 2., 3.],
        [4., 5., 6.]])

torch.Size([2, 3])

---------------------


Flattening tensor:

tensor([1., 2., 3., 4., 5., 6.])

torch.Size([6])

---------------------


Transposing tensor:

tensor([[[1., 4.],
         [2., 5.],
         [3., 6.]]])

torch.Size([1, 3, 2])

---------------------




### Conversion to numpy

In [ ]:
tensor = torch.Tensor([[[1,2,3], [4,5,6]]])

tensor.numpy()

array([[[1., 2., 3.],
        [4., 5., 6.]]], dtype=float32)

### Saving and loading

In [ ]:
torch.save(tensor, 'file')
torch.load('file')

# Use of GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
# GPU usage

device = torch.device("cuda")
gpu_tensor = torch.rand([2,3], device=device)

# Or

gpu_tensor = torch.rand([2,3])
gpu_tensor = gpu_tensor.to(device)

In [ ]:
# CPU usage

cpu_tensor = torch.rand([2,3])

print(f'1. Tensor: \n\n{cpu_tensor}\n\n{cpu_tensor.shape}\n\n{cpu_tensor.device}\n----------------------\n\n')

# Or

device = torch.device("cpu")
cpu_tensor = torch.rand([2,3], device=device)

print(f'2. Tensor: \n\n{cpu_tensor}\n\n{cpu_tensor.shape}\n\n{cpu_tensor.device}\n----------------------\n\n')

1. Tensor: 

tensor([[0.6184, 0.0448, 0.7337],
        [0.9791, 0.8658, 0.2710]])

torch.Size([2, 3])

cpu
----------------------


2. Tensor: 

tensor([[0.3161, 0.8425, 0.2236],
        [0.1400, 0.4040, 0.3202]])

torch.Size([2, 3])

cpu
----------------------




In [ ]:
# GPU usage

device = torch.device("cuda")
gpu_tensor = torch.rand([2,3], device=device)

print(f'1. Tensor: \n\n{gpu_tensor}\n\n{gpu_tensor.shape}\n\n{gpu_tensor.device}\n----------------------\n\n')

# Or

gpu_tensor = torch.rand([2,3])
gpu_tensor = gpu_tensor.to(device)

print(f'2. Tensor: \n\n{gpu_tensor}\n\n{gpu_tensor.shape}\n\n{gpu_tensor.device}\n----------------------\n\n')

1. Tensor: 

tensor([[0.5670, 0.8276, 0.6365],
        [0.4482, 0.7371, 0.8530]], device='cuda:0')

torch.Size([2, 3])

cuda:0
----------------------


2. Tensor: 

tensor([[0.6345, 0.2538, 0.2909],
        [0.7473, 0.0441, 0.2349]], device='cuda:0')

torch.Size([2, 3])

cuda:0
----------------------




### CPU and GPU comparison

In [ ]:
from time import time

In [ ]:

print(f'Tensor Shape: 5 x 5\n\n')

shape = (5,5)

cpu_tensor = torch.rand(shape, device='cpu')
gpu_tensor = torch.rand(shape, device='cuda')

print(f'CPU Tensor: \n\n{cpu_tensor}\n\n{cpu_tensor.shape}\n\n{cpu_tensor.device}\n----------------------\n\n')
print(f'GPU Tensor: \n\n{gpu_tensor}\n\n{gpu_tensor.shape}\n\n{gpu_tensor.device}\n----------------------\n\n')

cpu_start = time()

# Operation executed on cpu
cpu_x = cpu_tensor ** (cpu_tensor ** 5)

cpu_end = time()
cpu_time = cpu_end - cpu_start
print(f'> CPU spent time: {cpu_time:.5f}')


gpu_start = time()

# Operation executed on gpu
gpu_x = gpu_tensor ** (gpu_tensor ** 5)

gpu_end = time()
gpu_time = gpu_end - gpu_start

print(f'> GPU spent time: {gpu_time:.5f}')

1. Tensor Shape: 5 x 5


CPU Tensor: 

tensor([[0.3097, 0.6957, 0.1510, 0.3059, 0.5731],
        [0.3428, 0.1242, 0.5384, 0.8544, 0.2640],
        [0.1606, 0.5280, 0.5561, 0.9924, 0.3700],
        [0.4035, 0.1486, 0.4762, 0.0853, 0.8867],
        [0.8777, 0.9497, 0.8259, 0.4016, 0.7351]])

torch.Size([5, 5])

cpu
----------------------


GPU Tensor: 

tensor([[0.1295, 0.1211, 0.9141, 0.5435, 0.5450],
        [0.5277, 0.0666, 0.6347, 0.0755, 0.6900],
        [0.0245, 0.5635, 0.7334, 0.8506, 0.3531],
        [0.1996, 0.4658, 0.8008, 0.8238, 0.6044],
        [0.0626, 0.9038, 0.4107, 0.1039, 0.4986]], device='cuda:0')

torch.Size([5, 5])

cuda:0
----------------------


> CPU spent time: 0.00081
> GPU spent time: 0.00093


1. 5x5 tensor
2. 50x50 tensor
3. 500x500 tensor
4. 5000x5000 tensor

In [ ]:
def compare_cpu_gpu(shape):
  print(f'Tensor Shape: {shape}\n')

  cpu_tensor = torch.rand(shape, device='cpu')
  gpu_tensor = torch.rand(shape, device='cuda')

  cpu_start = time()
  cpu_x = cpu_tensor ** (cpu_tensor ** 5)
  cpu_end = time()
  cpu_time = cpu_end - cpu_start
  print(f'> CPU spent time: {cpu_time:.5f}')

  gpu_start = time()
  gpu_x = gpu_tensor ** (gpu_tensor ** 5)
  gpu_end = time()
  gpu_time = gpu_end - gpu_start
  print(f'> GPU spent time: {gpu_time:.5f}')
  print('\n-------------------------------')

In [ ]:
shape = (5,5)
compare_cpu_gpu(shape)

shape = (50,50)
compare_cpu_gpu(shape)

shape = (500,500)
compare_cpu_gpu(shape)

shape = (5000,5000)
compare_cpu_gpu(shape)

Tensor Shape: (5, 5)

> CPU spent time: 0.00013
> GPU spent time: 0.00009

-------------------------------
Tensor Shape: (50, 50)

> CPU spent time: 0.00127
> GPU spent time: 0.00072

-------------------------------
Tensor Shape: (500, 500)

> CPU spent time: 0.00521
> GPU spent time: 0.00071

-------------------------------
Tensor Shape: (5000, 5000)

> CPU spent time: 0.52835
> GPU spent time: 0.00088

-------------------------------


# AutoGrad

## Simple example

In [2]:
shape = (3,4)

X = torch.rand(shape, requires_grad=True)
Y = torch.rand(shape, requires_grad=True)
Z = torch.rand(shape, requires_grad=True)

a = X * Y
b = a + Z
c = torch.sum(b)

c.backward()

print(f'dc/dx=\n{X.grad}\n')
print(f'dc/dy=\n{Y.grad}\n')
print(f'dc/dz=\n{Z.grad}\n')

dc/dx=
tensor([[0.9758, 0.4437, 0.0220, 0.8924],
        [0.1086, 0.4977, 0.6528, 0.3650],
        [0.3060, 0.2496, 0.0436, 0.1209]])

dc/dy=
tensor([[0.0356, 0.4792, 0.4905, 0.8965],
        [0.1536, 0.0870, 0.9870, 0.9516],
        [0.2122, 0.1259, 0.8831, 0.5180]])

dc/dz=
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])



In [3]:
a

tensor([[0.0348, 0.2126, 0.0108, 0.8000],
        [0.0167, 0.0433, 0.6444, 0.3474],
        [0.0649, 0.0314, 0.0385, 0.0626]], grad_fn=<MulBackward0>)

### Zero grad

In [ ]:
print(X.grad.zero_())

print(Y.grad.zero_())

print(Z.grad.zero_())

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
shape = (2,3)

x = torch.rand(shape, requires_grad=True)
print(f'Tensor with grad active:\n{x}\n\n')

y = x + 1

print(f'Gradient from the operation y = x + 1:\ny={y}\n\n')

print(f'Operation: z = y ** x\n')
z = y ** x
z = z.mean()
z.backward()  # Accumulate the gradients
print(f'After computing the gradient, \ndz/dx={x.grad}')

Tensor with grad active:
tensor([[0.1708, 0.9496, 0.2902],
        [0.5272, 0.6329, 0.3551]], requires_grad=True)


Gradient from the operation y = x + 1:
y=tensor([[1.1708, 1.9496, 1.2902],
        [1.5272, 1.6329, 1.3551]], grad_fn=<AddBackward0>)


Operation: z = y ** x

After computing the gradient, 
dz/dx=tensor([[0.0520, 0.3628, 0.0861],
        [0.1601, 0.1996, 0.1051]])


## Skipping Gradient

In [13]:
shape = (3,4)

X = torch.rand(shape, requires_grad=True)
Y = torch.rand(shape, requires_grad=True)
Z = torch.rand(shape, requires_grad=True)

with torch.no_grad():
  a = X * Y
  b = a + Z
  c = torch.sum(b)

  print(f' > a: \n{a}\n')
  print(f' > a -> Requires Grad -> {a.requires_grad}\n\n')
  
  print(f' > b: \n{b}\n')
  print(f' > b -> Requires Grad -> {b.requires_grad}\n\n')

  print(f' > c: \n{c}\n')
  print(f' > c -> Requires Grad -> {c.requires_grad}\n\n')

  print(f' > Grad X: {X.grad}')
  print(f' > Grad Y: {Y.grad}')
  print(f' > Grad Z: {Z.grad}')

 > a: 
tensor([[0.2271, 0.3240, 0.1773, 0.0944],
        [0.2898, 0.5137, 0.2511, 0.0156],
        [0.1638, 0.2279, 0.0228, 0.2539]])

 > a -> Requires Grad -> False


 > b: 
tensor([[0.2864, 0.9831, 1.0513, 0.4324],
        [0.3456, 0.5651, 0.7667, 0.2691],
        [0.7428, 0.9393, 0.2039, 1.0663]])

 > b -> Requires Grad -> False


 > c: 
7.652011394500732

 > c -> Requires Grad -> False


 > Grad X: None
 > Grad Y: None
 > Grad Z: None


## Optimization case

In [ ]:
weights = torch.ones(5, requires_grad=True)

for epoch in range(3):
    model_output = (weights**2).sum()   # Example of model output
    loss = model_output / 5             # Example of loss computation
    
    # Backpropagation
    loss.backward()
    
    print(f' > Weights at epoch {epoch}: \n\n{weights}\n\n')
    print(f' > Weights grad at epoch {epoch}: \n\n{weights.grad}\n\n')

    # Model Optimization 
    with torch.no_grad():
        weights -= 0.1 * weights.grad
        print(f' > Weights updated at epoch {epoch}: \n\n{weights}\n\n')

    # ReInit gradient weight to ZERO
    # necessary for each optimization
    weights.grad.zero_()
    print(f' > Weights grad reset at epoch {epoch}: \n\n{weights.grad}\n\n\n-------------------------\n')

 > Weights at epoch 0: 

tensor([1., 1., 1., 1., 1.], requires_grad=True)


 > Weights grad at epoch 0: 

tensor([0.4000, 0.4000, 0.4000, 0.4000, 0.4000])


 > Weights updated at epoch 0: 

tensor([0.9600, 0.9600, 0.9600, 0.9600, 0.9600], requires_grad=True)


 > Weights grad reset at epoch 0: 

tensor([0., 0., 0., 0., 0.])


-------------------------

 > Weights at epoch 1: 

tensor([0.9600, 0.9600, 0.9600, 0.9600, 0.9600], requires_grad=True)


 > Weights grad at epoch 1: 

tensor([0.3840, 0.3840, 0.3840, 0.3840, 0.3840])


 > Weights updated at epoch 1: 

tensor([0.9216, 0.9216, 0.9216, 0.9216, 0.9216], requires_grad=True)


 > Weights grad reset at epoch 1: 

tensor([0., 0., 0., 0., 0.])


-------------------------

 > Weights at epoch 2: 

tensor([0.9216, 0.9216, 0.9216, 0.9216, 0.9216], requires_grad=True)


 > Weights grad at epoch 2: 

tensor([0.3686, 0.3686, 0.3686, 0.3686, 0.3686])


 > Weights updated at epoch 2: 

tensor([0.8847, 0.8847, 0.8847, 0.8847, 0.8847], requires_gr

In [ ]:
# With pytorch Optimizer
# 
# optimizer = torch.optim.SGD([weights], lr=0.1) [Example of Optimizator]
# 
# During training:
# optimizer.step()          [Update of weigths] 
#
# optimizer.zero_grad()     [ReInit grad to zero]